server:
  port: 9090
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/springdb
    username: andelarwanda
    password: andela123

app:
  jwt:
    secret: foodbookjwtsecretkey
  authorities:
    USER: USER
    VENDOR: VENDOR
    ADMIN: ADMIN
