server:
  port: ${PORT}
  error:
    include-message: always

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ENC(CwhC0SIdtxufYyevOoPgX9y8oG2cEu064NdN8PYqvdn71BkMJL8wxmUz2tpbgUrGTmp8En8bsyhThHq6qJEA4vRCMQMfGkiBjPqzSaOMkGEQV/HPiyzRvRm6Wy4qV8nYr7lXLUpT992uHNOuuWWCh4x7MzRu5GgQKJVi03bjgrQ=)
    username: ENC(5uwNmtdykdjahgINm3ygI/STVt4gr0TfnGWoBD2M6Kg9CzDP8+CETRLJFaeJ2WpM)
    password: ENC(SFhRlOR00MhwqnIqNqwol+dv8kWI3HC0xTibB/OGf/vViup/L/zU/EkyvQyE+30TLoQYErDzDguCVanLSmvmmw==)

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

app:
  jwt:
    secret: ENC(tOjyId8Q3UFv5vOGzILD94UUtoB1XVD1a3/OMRCdgY3dLrqVR0cgqRB97DYFVviTGVZTloUGRGP0pcyziH8NVw==)
  authorities:
    USER: USER
    VENDOR: VENDOR
    ADMIN: ADMIN


cloudinary:
  cloud_name: dmepvxtwv
  api_key: 315539454121522
  api_secret: loWqc4xiNEmb1YUa812FvHzrjd0
