server:
  port: ${PORT}
  error:
    include-message: always

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  ## 6yubfw4ztp17jlx9nc0d name
  ## pscale_pw_9qqJP1zHjeINtbzS1hJ5OONhcHpK13XZcvKNw4nt6rK pasword
  ##   jdbc:mysql://us-east.connect.psdb.cloud/food_book_app?sslMode=VERIFY_IDENTITY url
  datasource:
    url: ENC(+5NKj7rasml9qcoWQ0yhKslteMxVZkoSGa95UQ+Andqg8En6YSRiT4V/w8rKu4UKvsZOpyDsSlErqOZTKW7HRV2xzZGGbFug9EuBgRq8hXdi5YOc79oirvMykJK06bSvG4pdQLoHc2AzQdd2X6hT8Q==)
    username: ENC(gpKeGJTKijEjFxeuNtbMIJQZam8zGAFdNHzz+q1gt8F9BFkEvhu6M21c4fTm6PpIz6sPXomwRMIfowFo3jV0yw==)
    password: ENC(uvpRsZ7dtJ8qTXOCo/Ty4WZxZs/nZU2m6EIXLCiRNBugdRC1fTyNmJZvy4DroassUsF1fEC19ACsDjxX3w2Ay9gtCXEZ5z2as3zp4xbsYZv4q/fs8hAmPRPDbFNDTZTH)

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

app:
  jwt:
    secret: ENC(tOjyId8Q3UFv5vOGzILD94UUtoB1XVD1a3/OMRCdgY3dLrqVR0cgqRB97DYFVviTGVZTloUGRGP0pcyziH8NVw==)
  authorities:
    USER: USER
    VENDOR: VENDOR
    ADMIN: ADMIN


cloudinary:
  cloud_name: dmepvxtwv
  api_key: 315539454121522
  api_secret: loWqc4xiNEmb1YUa812FvHzrjd0
