server:
  port: ${PORT}
  error:
    include-message: always


spring:
  profiles:
    active: prod
  jpa:
    #    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: ENC(ahxodd4wWJlvVmGB+6bFPtXllVO/hfHEYkXQmOqoNf2qoy9fMzppqcht7PHvhHBDu2QEg08AWqleEaFDRfE5ZWo3wZshEklGARkLPspYNWIdnvof3/CmKnOeKh68D1WYOTm+IYOybWNMOG/mpA/kQ5V+7JflA0U/cY14OVuCVArkN9DyDhi03CZvVhw3SWOr)
    username: ENC(du2Ae1DHiukIYz+yELH4w/CPgqH+rouEftXT/L6rCUsDy7v9voNxN+K+PO1zu/qG)
    password: ENC(LOdf0fuDPHzEeQhnIy5htXSUCEI52i32afIbBPXijpCbs9fcL5x4KvnnusSa4dq3i0BgBrBi4RKeRqUpj2KTAw==)

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

app:
  jwt:
    secret: ENC(tOjyId8Q3UFv5vOGzILD94UUtoB1XVD1a3/OMRCdgY3dLrqVR0cgqRB97DYFVviTGVZTloUGRGP0pcyziH8NVw==)
  authorities:
    USER: USER
    VENDOR: VENDOR
    ADMIN: ADMIN


cloudinary:
  cloud_name: dmepvxtwv
  api_key: 315539454121522
  api_secret: loWqc4xiNEmb1YUa812FvHzrjd0
